function [fitresult, gof] = createFit(xi, yi, fStar,startpoint,withpicture)
%CREATEFIT(XI,YI,FSTAR)
%  Create a fit.
%
%  Data for 'gausssurf' fit:
%      X Input : xi
%      Y Input : yi
%      Z Output: fStar
%      starpoint :startpoint 
%       withpicture is 0 then no picture will show
%      guass(x,y) = a*exp(-((x-x0).^2/2/sigmax^2 + (y-y0).^2/2/sigmay^2)) + b
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Apr-2013 14:25:40
%  And changed by lifan on 13-Apr-2013 21:26 


%% Fit: 'gausssurf'.
[xData, yData, zData] = prepareSurfaceData( xi, yi, fStar );

% Set up fittype and options.
ft = fittype( 'a*exp(-((x-x0).^2/2/sigmax^2 + (y-y0).^2/2/sigmay^2)) + b', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf];
opts.StartPoint = startpoint;
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );
if withpicture
% Create a figure for the plots.
figure( 'Name', 'gausssurf' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'gausssurf', 'fStar vs. xi, yi', 'Location', 'NorthEast' );
% Label axes
xlabel( 'xi' );
ylabel( 'yi' );
zlabel( 'fStar' );
grid on
view( -21.0, 0 );

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, [xData, yData], zData, 'Style', 'Residual' );
legend( h, 'gausssurf - residuals', 'Location', 'NorthEast' );
% Label axes
xlabel( 'xi' );
ylabel( 'yi' );
zlabel( 'fStar' );
grid on
view( -21.0, 0 );
else 
end
end


